# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Talx
email: haim.daniel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software grunts about Linux and Opensource. Some experiments in Openstack
  along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haim0n.gihub.io" # the base hostname & protocol for your site
github_username:  haim0n

# Build settings
markdown: kramdown
